CREATE DATABASE [LucasNotes.NoteDb] ;
GO

USE [LucasNotes.NoteDb];
GO

IF OBJECT_ID(N'[dbo].[Note]', N'U') IS NULL
BEGIN

	CREATE TABLE [dbo].[Note](
		[Id] [int] IDENTITY(1,1) NOT NULL,
		[UserId] [int] NOT NULL,
		[FolderId] [int] NOT NULL,
		[Name] [nvarchar](50) NOT NULL,
		[Content] [nvarchar](max) NULL,
		[Tag] [nvarchar](50) NULL,
	CONSTRAINT [PK_Note] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
	) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]


END
GO

IF OBJECT_ID(N'[dbo].[Folder]', N'U') IS NULL
BEGIN

	CREATE TABLE [dbo].[Folder](
		[Id] [int] IDENTITY(1,1) NOT NULL,
		[Name] [nvarchar](50) NOT NULL,
		[ParentId] [int] NULL,
	CONSTRAINT [PK_Folder] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
	) ON [PRIMARY]

END
GO
